version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin 786960477911.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - docker build -t pen-test-app:latest .
      - docker tag pen-test-app:latest 786960477911.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/pen-test-app:latest
  post_build:
    commands:
      - echo Pushing the Docker image...
      - docker push 786960477911.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/pen-test-app:latest
      - echo Writing image definitions file...
      - printf '[{"name":"frontend","imageUri":"786960477911.dkr.ecr.%s.amazonaws.com/pen-test-app:latest"}]' $AWS_DEFAULT_REGION > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
